# ===========================================================================
#  globals.tcl -- everything about THIS design and THIS technology, in one
#  place. Every other script reads from the $design(...) array and sets
#  nothing of its own.
#
#  This is the same convention the polHEEPo / HEEPatia SoC flow uses
#  (implementation/common/<chip>.tcl there). Learn it here on a 500-cell
#  block and it will still be the file you edit on a 500 000-cell chip.
#
#  Overridable from the shell:
#    IHP_PDK_ROOT    where the PDK lives          (default /eda/dk/ihp-sg13g2)
#    SG13G2_CORNER   the setup corner             (default slow_1p08V_125C)
#    PNR_UTIL        target core utilisation      (default 0.60)
#    PNR_ASPECT      core aspect ratio            (default 1.00)
# ===========================================================================

global design

# --- what we are placing and routing ------------------------------------
set design(TOPLEVEL) cordic_accel

# The lab root, two levels up from implementation/innovus/.
if {[info exists ::env(LAB_ROOT)]} {
  set design(LAB_ROOT) [string trim $::env(LAB_ROOT)]
} else {
  set design(LAB_ROOT) [file normalize ../..]
}

# Design Compiler's outputs are our inputs. Nothing here is generated by
# Innovus; if these files are missing, run `make synth` in lab1/ first.
set design(SYN_DIR)     $design(LAB_ROOT)/implementation/design_compiler
set design(netlist)     $design(SYN_DIR)/netlist/$design(TOPLEVEL).v
set design(default_sdc) $design(SYN_DIR)/netlist/$design(TOPLEVEL).sdc

# --- where the technology lives -----------------------------------------
if {[info exists ::env(IHP_PDK_ROOT)]} {
  set design(PDK) [string trim $::env(IHP_PDK_ROOT)]
} else {
  set design(PDK) /eda/dk/ihp-sg13g2
}
set design(PDK_LIB) $design(PDK)/libs.ref

if {![file isdirectory $design(PDK_LIB)]} {
  error "cannot find $design(PDK_LIB) -- set IHP_PDK_ROOT to your PDK"
}

# The PVT corner to sign setup off at. Same three the synthesis uses; keep
# them in step, because a netlist built at slow and routed at typ is not a
# result.
if {[info exists ::env(SG13G2_CORNER)]} {
  set design(CORNER) [string trim $::env(SG13G2_CORNER)]
} else {
  set design(CORNER) slow_1p08V_125C
}

# Liberty per corner. Innovus reads .lib directly -- unlike Design Compiler
# it does not want the compiled .db, so there is no library-compile step
# here.
set design(LIB_DIR)  $design(PDK_LIB)/sg13g2_stdcell/lib
set design(lib_slow) $design(LIB_DIR)/sg13g2_stdcell_slow_1p08V_125C.lib
set design(lib_typ)  $design(LIB_DIR)/sg13g2_stdcell_typ_1p20V_25C.lib
set design(lib_fast) $design(LIB_DIR)/sg13g2_stdcell_fast_1p32V_m40C.lib

# The operating points those three files were characterised at. They have to
# match the file names or the analysis views are a lie.
set design(opcond_slow) {1.08 125}
set design(opcond_typ)  {1.20  25}
set design(opcond_fast) {1.32 -40}

set design(mmmc_view_file) [file normalize [file dirname [info script]]/lab1.view]

# --- physical: LEF ------------------------------------------------------
# The technology LEF first (layers, vias, design rules, the site), then the
# cell LEFs (one abstract per standard cell: outline, pins, blockages).
set design(ALL_LEFS) {}
lappend design(ALL_LEFS) $design(PDK_LIB)/sg13g2_stdcell/lef/sg13g2_tech.lef
lappend design(ALL_LEFS) $design(PDK_LIB)/sg13g2_stdcell/lef/sg13g2_stdcell.lef

set design(ALL_GDS) {}
lappend design(ALL_GDS) $design(PDK_LIB)/sg13g2_stdcell/gds/sg13g2_stdcell.gds

# --- physical: if you added an SRAM -------------------------------------
# Uncomment and set the macro you instantiated in
# implementation/tech/sg13g2/sram_wrapper_sg13g2.sv. The LEF gives Innovus
# the outline and the pins; the Liberty gives it the timing; the GDS is for
# the final stream-out. All three, or the macro is not really in the design.
#
#   set design(SRAM_MACRO) RM_IHPSG13_1P_1024x32_c2_bm_bist
#   lappend design(ALL_LEFS) $design(PDK_LIB)/sg13g2_sram/lef/$design(SRAM_MACRO).lef
#   lappend design(ALL_GDS)  $design(PDK_LIB)/sg13g2_sram/gds/$design(SRAM_MACRO).gds
#   set design(lib_sram_slow) $design(PDK_LIB)/sg13g2_sram/lib/${SRAM_MACRO}_slow_1p08V_125C.lib
#   ... and the matching typ/fast, appended to the library sets in lab1.view
#
# `ls $IHP_PDK_ROOT/libs.ref/sg13g2_sram/lib/` tells you the exact corner
# suffixes -- they are not always spelled the way the standard cells are.
set design(HAS_MACROS) [info exists design(SRAM_MACRO)]

# --- power nets ---------------------------------------------------------
# Two nets, flat, no power domains: this block is either clocked or it is
# not (see §5c of the Design Compiler README). A chip with retention or
# power gating would bring a UPF file here and `read_power_intent` in
# init.tcl -- that is what the SoC flow does, and it is the one step of that
# flow this lab leaves out on purpose.
set design(all_power_nets)  {VDD}
set design(all_ground_nets) {VSS}

# --- the cells the tools are allowed to add themselves ------------------
# Read straight out of the LEF:
#   grep -oE '^MACRO sg13g2_(fill|decap|antenna|tie|buf|inv)[a-z0-9_]*' \
#        $IHP_PDK_ROOT/libs.ref/sg13g2_stdcell/lef/sg13g2_stdcell.lef
#
# Fillers, largest first: add_fillers walks the list in order and a greedy
# fill with the big ones leaves fewer gaps.
set design(fillers)  {sg13g2_fill_8 sg13g2_fill_4 sg13g2_fill_2 sg13g2_fill_1}
set design(decaps)   {sg13g2_decap_8 sg13g2_decap_4}
# Tie cells, as cell:pin. `add_tieoffs' wants the OUTPUT PIN named, not just
# the cell -- give it the cell alone and it warns
#     **WARN: (IMPSP-5230): Only cell name sg13g2_tiehi has been specified.
#     Please also specify cell pin like cellName:cellPin.
# and then fails with IMPSP-5227. The pin names are in the LEF and they are
# not the obvious ones:
#     grep -A12 '^MACRO sg13g2_tiehi' $IHP_PDK_ROOT/.../sg13g2_stdcell.lef
set design(tie_cells) {sg13g2_tiehi:L_HI sg13g2_tielo:L_LO}
set design(antenna_cell) sg13g2_antennanp

# SG13G2 has no well-tap and no end-cap cells: the rows abut and the wells
# are tied inside each cell. Do not go looking for `sg13g2_tapcell` -- it
# does not exist, and a flow copied from a PDK that has one will fail here.
set design(tap_cells) {}

# CTS drivers. There is no dedicated clock-buffer family in this library, so
# the clock tree is built from the ordinary buffers and inverters. Only the
# stronger ones: a clock tree made of _1 drives is a clock tree made of
# thousands of cells.
set design(cts_buffers)   {sg13g2_buf_4 sg13g2_buf_8 sg13g2_buf_16}
set design(cts_inverters) {sg13g2_inv_4 sg13g2_inv_8 sg13g2_inv_16}

# --- the metal stack ----------------------------------------------------
# From sg13g2_tech.lef. Seven routing layers; the alternating preferred
# directions are what make a two-layer-at-a-time router work.
#
#   Metal1     HORIZONTAL   min width 0.16   <- standard cell rails and pins
#   Metal2     VERTICAL     min width 0.20
#   Metal3     HORIZONTAL   min width 0.20
#   Metal4     VERTICAL     min width 0.20
#   Metal5     HORIZONTAL   min width 0.20
#   TopMetal1  VERTICAL     min width 1.64   <- thick metal, pitch 3.28
#   TopMetal2  HORIZONTAL   min width 2.00   <- thick metal, pitch 4.00
#
# Signals get Metal1..Metal5. The two thick top layers are left for the
# power grid: they are the low-resistance ones, and their coarse pitch makes
# them nearly useless for signal routing anyway.
set design(route_bottom_layer) Metal1
set design(route_top_layer)    Metal5

# The ring goes on the two thick top layers -- they carry the whole block's
# current and they are the lowest-resistance metal in the stack.
#
# The stripes do NOT. Putting vertical stripes on TopMetal1 alongside the
# vertical ring segment puts two thick-metal shapes in the same narrow
# channel, and TopMetal1's minimum spacing is 1.64 um -- the same as its
# minimum width. The result is 35 ParallelRunLength spacing violations along
# the left edge, every one of them between the ring and the first stripe.
#
# Metal4 is vertical, its minimum width is 0.20 um and its spacing rules are
# the ordinary thin-metal ones, so a stripe grid fits without argument. The
# cost is that Metal4 is also a signal layer: every stripe is routing
# resources the router no longer has. At 60 % utilisation on a block this
# size that is free; on a congested design it is the trade-off to tune.
set design(pg_ring_h_layer)    TopMetal2
set design(pg_ring_v_layer)    TopMetal1
set design(pg_stripe_layer)    Metal4
set design(pg_followpin_layer) Metal1

# Power ring and stripe geometry, in microns. These are the numbers to play
# with if `check_drc` complains after the power plan, or if the IR drop
# matters to you later.
# Ring: thick metal, so both numbers must clear TopMetal1's 1.64 um minimum
# width and minimum spacing. 3.0 and 2.0 do.
set design(pg_ring_width)      3.00
set design(pg_ring_spacing)    2.00
# Stripes: Metal4, minimum width 0.20 um. 1.0 is generous for the current a
# block this size draws and still leaves the router most of the layer.
set design(pg_stripe_width)    1.00
set design(pg_stripe_spacing)  1.00
set design(pg_stripe_pitch)    50.00

# --- floorplan ----------------------------------------------------------
# Utilisation is the fraction of the core area the standard cells occupy
# before routing. 0.60 is a comfortable number for a first run: enough room
# that the router does not fight you, not so much that the block is mostly
# filler. Push it up once the flow closes, and watch congestion.
if {[info exists ::env(PNR_UTIL)]}   { set design(util)   [string trim $::env(PNR_UTIL)] }   else { set design(util)   0.60 }
if {[info exists ::env(PNR_ASPECT)]} { set design(aspect) [string trim $::env(PNR_ASPECT)] } else { set design(aspect) 1.00 }

# Distance from the core edge to the die edge, all four sides. The power
# ring lives in this channel, so it has to hold two rings plus their
# spacings: 2 * (width + spacing) with a little room to spare.
set design(core_to_die) [expr {2 * ($design(pg_ring_width) + $design(pg_ring_spacing)) + 5.0}]

set design(site) CoreSite

# --- CTS targets --------------------------------------------------------
# In ns. Skew first: everything the clock tree does is in service of getting
# the same edge to every flop at the same time. The transition limit keeps
# the tree's own slew under control -- a slow clock edge is jitter you
# cannot budget for.
set design(cts_target_skew)      0.10

# 0.40 ns, and the number is not a preference -- it is a property of this
# library. SG13G2 ships its integrated clock gate in ONE drive strength:
#
#     sg13g2_lgcp_1    sg13g2_slgcp_1      and that is the whole list
#
# so the weakest driver in the clock tree is fixed, and it still has to
# drive whatever CTS puts after it. Ask for 0.15 ns and ccopt refuses to
# start:
#
#     **ERROR: (IMPCCOPT-1209): Non-leaf slew time target of 0.150ns is too
#     low ... The largest clock gate is unable to drive the largest inverter
#     ... increase the slew target to at least 0.317ns or remove these
#     driver cells from the CTS cell lists: sg13g2_inv_16 sg13g2_inv_8
#     **ERROR: (IMPCCOPT-1013): ... CTS will now terminate.
#
# and the log spells out the minimum per corner ("Too low; min: 0.319ns").
# Two ways out: raise the target, or drop the strong inverters so the gate
# only ever drives something it can. Raising it is the better trade here --
# the strong cells are what keep the tree shallow.
#
# If you retarget this flow to another PDK, expect this number to change,
# and let the tool tell you: it prints the minimum it will accept.
set design(cts_target_max_trans) 0.40

# --- outputs ------------------------------------------------------------
set design(REPORT_DIR) artefacts/reports
set design(DB_DIR)     artefacts/db
set design(EXPORT_DIR) artefacts/export
set design(METRIC_DIR) artefacts/metrics
